# Project dimensions
PLY_THICKNESS = 9
ROUTE_DEPTH = PLY_THICKNESS / 2

# Box dimensions
BOX_X = 490
BOX_Y = 350
BOX_Z = 540

# Divider dimensions
TOP_DIVIDER_X = BOX_Y - PLY_THICKNESS
TOP_DIVIDER_Y = 300
TOP_DIVIDER_Z = 300

# Calculated dimensions
OFFSET = PLY_THICKNESS - ROUTE_DEPTH
PANEL_Y = BOX_Y - 2*OFFSET
PANEL_Z = BOX_Z - OFFSET